services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=twym
      - POSTGRES_USER=twym
      - POSTGRES_PASSWORD=postgres
    container_name: twym-connect-db
    volumes:
      - .pgdata:/var/lib/postgresql
    ports:
      - '5432:5432'
    networks:
      - twym-connect-network

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
#    restart: always
#    container_name: twym-connect-api
#    ports:
#      - '3000:3000'
#    depends_on:
#      - db
#    volumes:
#      - ./src:/app/src
#    networks:
#      - twym-connect-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: twym-connect-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@twym.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - twym-connect-network

networks:
  twym-connect-network:
    driver: bridge
